-- Create table for application configuration
-- This table will store business details, hours, and social media links.
-- It is designed to have a single row.

create table public.configuracion (
  id bigint generated by default as identity primary key,
  nombre_negocio text not null default 'Autolavado Gochi',
  rif text default '',
  telefono text default '',
  email text default '',
  direccion text default '',
  instagram text default '',
  facebook text default '',
  whatsapp text default '',
  hora_apertura time default '08:00',
  hora_cierre time default '18:00',
  dias_laborables text[] default array['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.configuracion enable row level security;

-- Policy: Everyone can read configuration
create policy "Enable read access for all users" on public.configuracion
  for select using (true);

-- Policy: Authenticated users can update configuration (assuming admin access or open for now as per previous context)
-- For simplicity in this dev phase, allowing update for anon/authenticated if it's the app.
-- Ideally should be admin only.
create policy "Enable update for all users" on public.configuracion
  for update using (true) with check (true);

-- Policy: Allow insert only if table is empty (to ensure single row), but easiest is just allow insert and UI manages ID=1.
create policy "Enable insert for all users" on public.configuracion
  for insert with check (true);

-- Insert default row if not exists (This won't run via Supabase SQL Editor usually if running multiple times, but good for init)
insert into public.configuracion (id, nombre_negocio)
select 1, 'Autolavado Gochi'
where not exists (select 1 from public.configuracion);
