
-- 8. Tabla: Movimientos de Inventario (inventory_movements) -> 'movimientos'
create table public.movimientos (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('entrada', 'salida')),
  producto_id bigint references public.productos(id) on delete restrict,
  cantidad int not null,
  motivo text,
  fecha timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Políticas para Movimientos
alter table public.movimientos enable row level security;

create policy "Acceso total a movimientos" on public.movimientos
  for all using (true) with check (true);
