-- 9. Tabla: Pedidos (orders) -> 'pedidos'
create table public.pedidos (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.clientes(id) on delete set null,
  tipo text not null check (tipo in ('walk-in', 'appointment')), -- 'walk-in' = por llegada, 'appointment' = cita
  estado text not null default 'Pendiente' check (estado in ('Pendiente', 'Confirmada', 'En Proceso', 'Completada', 'Cancelada')),
  fecha_programada date, -- Para citas
  hora_programada time,  -- Para citas
  total numeric not null default 0,
  notas text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. Tabla: Detalle de Pedidos (order_items) -> 'detalle_pedidos'
create table public.detalle_pedidos (
  id bigint generated by default as identity primary key,
  pedido_id bigint references public.pedidos(id) on delete cascade not null,
  servicio_id bigint references public.servicios(id) on delete set null,
  precio_unitario numeric not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.pedidos enable row level security;
alter table public.detalle_pedidos enable row level security;

-- Políticas (Public access for simplicity as requested, refine for auth later)
create policy "Acceso total a pedidos" on public.pedidos
  for all using (true) with check (true);

create policy "Acceso total a detalle_pedidos" on public.detalle_pedidos
  for all using (true) with check (true);

-- Enable Realtime
alter publication supabase_realtime add table public.pedidos;
alter publication supabase_realtime add table public.detalle_pedidos;
