-- Habilitar extensión UUID si no está habilitada
create extension if not exists "uuid-ossp";

-- 1. Tabla: Clientes (customers) -> 'clientes'
create table public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  email text,
  telefono text,
  vehiculo text,
  tipo_vehiculo text,
  placa text,
  estado text default 'Normal' check (estado in ('VIP', 'Regular', 'Normal')),
  visitas int default 0,
  imagen_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabla: Servicios (services) -> 'servicios'
create table public.servicios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  precio numeric not null default 0,
  es_popular boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabla: Productos (products) -> 'productos'
create table public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  precio numeric not null default 0,
  imagen_url text,
  categoria text,
  stock int default 0,
  codigo_barras text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Tabla: Usuarios (users) -> 'usuarios'
-- Esta tabla extiende la funcionalidad de auth.users de Supabase
create table public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  rol text default 'empleado' check (rol in ('admin', 'empleado')),
  email text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Tabla: Configuración (settings) -> 'configuracion'
create table public.configuracion (
  id bigint generated by default as identity primary key,
  nombre_negocio text default 'Autolavado Gochi',
  rif text,
  telefono text,
  email text,
  direccion text,
  instagram text,
  facebook text,
  whatsapp text,
  hora_apertura time default '08:00',
  hora_cierre time default '18:00',
  dias_laborales text[] default array['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insertar configuración por defecto si no existe (id 1)
insert into public.configuracion (id, nombre_negocio)
values (1, 'Autolavado Gochi')
on conflict (id) do nothing;

-- 6. Tabla: Ventas (sales) -> 'ventas'
create table public.ventas (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.clientes(id) on delete set null,
  usuario_id uuid references public.usuarios(id) on delete set null,
  total numeric not null default 0,
  metodo_pago text,
  fecha timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Tabla: Detalle de Ventas (sale_items) -> 'detalle_ventas'
create table public.detalle_ventas (
  id bigint generated by default as identity primary key,
  venta_id bigint references public.ventas(id) on delete cascade not null,
  producto_id bigint references public.productos(id) on delete set null,
  servicio_id bigint references public.servicios(id) on delete set null,
  cantidad int default 1,
  precio_unitario numeric not null default 0,
  subtotal numeric generated always as (cantidad * precio_unitario) stored
);

-- Habilitar Row Level Security (RLS)
alter table public.clientes enable row level security;
alter table public.servicios enable row level security;
alter table public.productos enable row level security;
alter table public.usuarios enable row level security;
alter table public.configuracion enable row level security;
alter table public.ventas enable row level security;
alter table public.detalle_ventas enable row level security;

-- Políticas de Seguridad (RLS Policies)
-- Por defecto, permitiremos lectura y escritura pública para facilitar el desarrollo inicial.
-- NOTA: En producción, deberías restringir esto a usuarios autenticados.

-- Políticas para Clientes
create policy "Acceso total a clientes" on public.clientes
  for all using (true) with check (true);

-- Políticas para Servicios
create policy "Acceso total a servicios" on public.servicios
  for all using (true) with check (true);

-- Políticas para Productos
create policy "Acceso total a productos" on public.productos
  for all using (true) with check (true);

-- Políticas para Usuarios
create policy "Acceso total a usuarios" on public.usuarios
  for all using (true) with check (true);

-- Políticas para Configuración
create policy "Acceso total a configuracion" on public.configuracion
  for all using (true) with check (true);

-- Políticas para Ventas
create policy "Acceso total a ventas" on public.ventas
  for all using (true) with check (true);

-- Políticas para Detalle de Ventas
create policy "Acceso total a detalle_ventas" on public.detalle_ventas
  for all using (true) with check (true);

-- Trigger para crear usuario en public.usuarios cuando se registra en auth.users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.usuarios (id, email, nombre)
  values (new.id, new.email, new.raw_user_meta_data->>'nombre');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
