-- Create table for Consumables (Insumos)
create table if not exists public.insumos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  stock numeric default 0,
  unidad text default 'unidad', -- litros, ml, caja, pieza, etc.
  stock_minimo numeric default 5,
  costo numeric default 0, -- Costo de compra
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.insumos enable row level security;

create policy "Enable read access for all authenticated users"
  on public.insumos for select
  to authenticated
  using (true);

create policy "Enable insert for authenticated users"
  on public.insumos for insert
  to authenticated
  with check (true);

create policy "Enable update for authenticated users"
  on public.insumos for update
  to authenticated
  using (true);

create policy "Enable delete for authenticated users"
  on public.insumos for delete
  to authenticated
  using (true);
