-- Migration: Refactor Customers to Support Multiple Phones and Vehicles
-- Date: 2025-12-16
-- Description: Creates vehiculos table, migrates existing vehicle data, updates clientes table

-- =====================================================
-- STEP 1: Drop existing vehiculos table if it exists (clean slate)
-- =====================================================
DROP TABLE IF EXISTS public.vehiculos CASCADE;

-- =====================================================
-- STEP 2: Create vehiculos table with all columns
-- =====================================================
CREATE TABLE public.vehiculos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  placa TEXT NOT NULL UNIQUE,
  imagenes TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Create indexes for faster lookups
CREATE INDEX idx_vehiculos_cliente_id ON public.vehiculos(cliente_id);
CREATE INDEX idx_vehiculos_placa ON public.vehiculos(placa);

-- =====================================================
-- STEP 3: Migrate existing vehicle data from clientes
-- =====================================================
-- Only migrate if there are customers with vehicle data
INSERT INTO public.vehiculos (cliente_id, tipo, placa, imagenes)
SELECT 
  id,
  COALESCE(tipo_vehiculo, 'No especificado'),
  COALESCE(placa, 'SIN-PLACA-' || id::TEXT),
  COALESCE(imagenes, '{}')
FROM public.clientes
WHERE vehiculo IS NOT NULL AND vehiculo != ''
  AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clientes' AND column_name = 'vehiculo');

-- =====================================================
-- STEP 4: Add telefonos column (array) to clientes
-- =====================================================
-- First, add the new column if it doesn't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clientes' AND column_name = 'telefonos') THEN
    ALTER TABLE public.clientes ADD COLUMN telefonos TEXT[] DEFAULT '{}';
  END IF;
END $$;

-- Migrate existing phone data to array format
UPDATE public.clientes 
SET telefonos = ARRAY[telefono]
WHERE telefono IS NOT NULL AND telefono != ''
  AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clientes' AND column_name = 'telefono');

-- =====================================================
-- STEP 5: Remove old vehicle and phone columns from clientes
-- =====================================================
ALTER TABLE public.clientes DROP COLUMN IF EXISTS vehiculo;
ALTER TABLE public.clientes DROP COLUMN IF EXISTS tipo_vehiculo;
ALTER TABLE public.clientes DROP COLUMN IF EXISTS placa;
ALTER TABLE public.clientes DROP COLUMN IF EXISTS telefono;

-- =====================================================
-- STEP 6: Enable RLS on vehiculos table
-- =====================================================
ALTER TABLE public.vehiculos ENABLE ROW LEVEL SECURITY;

-- Drop policy if exists to avoid conflicts
DROP POLICY IF EXISTS "Acceso total a vehiculos" ON public.vehiculos;

-- Create permissive policy for vehiculos
CREATE POLICY "Acceso total a vehiculos" 
ON public.vehiculos 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- =====================================================
-- STEP 7: Create storage bucket for vehicle photos
-- =====================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('vehiculos', 'vehiculos', true)
ON CONFLICT (id) DO NOTHING;

-- Drop existing storage policies to avoid conflicts
DROP POLICY IF EXISTS "Acceso público a vehiculos" ON storage.objects;
DROP POLICY IF EXISTS "Subida pública a vehiculos" ON storage.objects;
DROP POLICY IF EXISTS "Modificación pública a vehiculos" ON storage.objects;
DROP POLICY IF EXISTS "Eliminación pública a vehiculos" ON storage.objects;

-- Storage policies for vehiculos bucket
CREATE POLICY "Acceso público a vehiculos" 
ON storage.objects 
FOR SELECT 
USING (bucket_id = 'vehiculos');

CREATE POLICY "Subida pública a vehiculos" 
ON storage.objects 
FOR INSERT 
WITH CHECK (bucket_id = 'vehiculos');

CREATE POLICY "Modificación pública a vehiculos" 
ON storage.objects 
FOR UPDATE 
USING (bucket_id = 'vehiculos');

CREATE POLICY "Eliminación pública a vehiculos" 
ON storage.objects 
FOR DELETE 
USING (bucket_id = 'vehiculos');

-- =====================================================
-- STEP 8: Add trigger for updated_at on vehiculos
-- =====================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::TEXT, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_vehiculos_updated_at ON public.vehiculos;
CREATE TRIGGER update_vehiculos_updated_at
BEFORE UPDATE ON public.vehiculos
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- Migration Complete
-- =====================================================
-- Summary:
-- ✓ Dropped and recreated vehiculos table with proper columns
-- ✓ Migrated existing vehicle data from clientes
-- ✓ Added telefonos array column to clientes
-- ✓ Removed old vehicle and phone columns from clientes
-- ✓ Configured RLS policies
-- ✓ Created vehiculos storage bucket with policies
-- ✓ Added auto-update trigger for updated_at
