-- UNIFIED SCHEMA FOR AUTOLAVADO GOCHI
-- Combined from multiple source files by Supabase Assistant

-- 1. EXTENSIONS
create extension if not exists "uuid-ossp";

-- 2. CORE TABLES (from supabase_schema.sql)
-- Clientes
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  email text,
  telefono text,
  vehiculo text,
  tipo_vehiculo text,
  placa text,
  estado text default 'Normal' check (estado in ('VIP', 'Regular', 'Normal')),
  visitas int default 0,
  imagen_url text, -- Kept for backward compatibility
  imagenes text[] default '{}', -- Added from storage.sql
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Servicios
create table if not exists public.servicios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  precio numeric not null default 0,
  es_popular boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Productos
create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  precio numeric not null default 0,
  imagen_url text,
  categoria text,
  stock int default 0,
  codigo_barras text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Usuarios (Legacy/Simple Auth)
create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  rol text default 'empleado' check (rol in ('admin', 'empleado')),
  email text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Profiles (RBAC Auth - from rbac.sql)
create table if not exists public.profiles (
  id uuid not null references auth.users(id) on delete cascade primary key,
  email text,
  role text not null check (role in ('admin', 'worker')) default 'worker',
  nombre text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Configuracion (Merged)
create table if not exists public.configuracion (
  id bigint generated by default as identity primary key,
  nombre_negocio text not null default 'Autolavado Gochi',
  rif text default '',
  telefono text default '',
  email text default '',
  direccion text default '',
  instagram text default '',
  facebook text default '',
  whatsapp text default '',
  hora_apertura time default '08:00',
  hora_cierre time default '18:00',
  dias_laborales text[] default array['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ventas
create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.clientes(id) on delete set null,
  usuario_id uuid references public.usuarios(id) on delete set null,
  total numeric not null default 0,
  metodo_pago text,
  fecha timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Detalle Ventas
create table if not exists public.detalle_ventas (
  id bigint generated by default as identity primary key,
  venta_id bigint references public.ventas(id) on delete cascade not null,
  producto_id bigint references public.productos(id) on delete set null,
  servicio_id bigint references public.servicios(id) on delete set null,
  cantidad int default 1,
  precio_unitario numeric not null default 0,
  subtotal numeric generated always as (cantidad * precio_unitario) stored
);

-- 3. MODULE TABLES

-- Insumos (from supabase_insumos.sql)
create table if not exists public.insumos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  stock numeric default 0,
  unidad text default 'unidad',
  stock_minimo numeric default 5,
  costo numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Pedidos (from supabase_orders.sql)
create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.clientes(id) on delete set null,
  tipo text not null check (tipo in ('walk-in', 'appointment')),
  estado text not null default 'Pendiente' check (estado in ('Pendiente', 'Confirmada', 'En Proceso', 'Completada', 'Cancelada')),
  fecha_programada date,
  hora_programada time,
  total numeric not null default 0,
  notas text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Detalle Pedidos
create table if not exists public.detalle_pedidos (
  id bigint generated by default as identity primary key,
  pedido_id bigint references public.pedidos(id) on delete cascade not null,
  servicio_id bigint references public.servicios(id) on delete set null,
  precio_unitario numeric not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Movimientos (from supabase_movements.sql)
create table if not exists public.movimientos (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('entrada', 'salida')),
  producto_id bigint references public.productos(id) on delete cascade,
  cantidad int not null,
  motivo text,
  fecha timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. STORAGE (from storage files)

-- Bucket: productos
insert into storage.buckets (id, name, public)
values ('productos', 'productos', true)
on conflict (id) do nothing;

-- Bucket: clientes
insert into storage.buckets (id, name, public)
values ('clientes', 'clientes', true)
on conflict (id) do nothing;

-- 5. FUNCTIONS & TRIGGERS

-- Decrement Stock (RPC)
create or replace function decrement_stock(p_id bigint, cant int)
returns void as $$
begin
  update public.productos
  set stock = stock - cant
  where id = p_id;
end;
$$ language plpgsql;

-- Admin Check Helper
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- Handle New User (UNIFIED)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  -- Insert into legacy users table
  insert into public.usuarios (id, email, nombre, rol)
  values (new.id, new.email, new.raw_user_meta_data->>'nombre', 'empleado')
  on conflict (id) do nothing;

  -- Insert into profiles table
  insert into public.profiles (id, email, role, nombre)
  values (new.id, new.email, 'worker', new.raw_user_meta_data->>'nombre')
  on conflict (id) do nothing;
  
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to recreate
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. SECURITY (RLS) & POLICIES

-- Enable RLS
alter table public.clientes enable row level security;
alter table public.servicios enable row level security;
alter table public.productos enable row level security;
alter table public.usuarios enable row level security;
alter table public.configuracion enable row level security;
alter table public.ventas enable row level security;
alter table public.detalle_ventas enable row level security;
alter table public.insumos enable row level security;
alter table public.pedidos enable row level security;
alter table public.detalle_pedidos enable row level security;
alter table public.movimientos enable row level security;
alter table public.profiles enable row level security;

-- Policies (Permissive + RBAC mixed where appropriate)
-- Using permissive ('true') for development as requested in original files, plus RBAC logic.

-- Clientes
create policy "Acceso total a clientes" on public.clientes for all using (true) with check (true);

-- Servicios
create policy "Acceso total a servicios" on public.servicios for all using (true) with check (true);

-- Productos
create policy "Acceso total a productos" on public.productos for all using (true) with check (true);

-- Usuarios
create policy "Acceso total a usuarios" on public.usuarios for all using (true) with check (true);

-- Configuracion
create policy "Acceso total a configuracion" on public.configuracion for all using (true) with check (true);

-- Ventas
create policy "Acceso total a ventas" on public.ventas for all using (true) with check (true);

-- Detalle Ventas
create policy "Acceso total a detalle_ventas" on public.detalle_ventas for all using (true) with check (true);

-- Insumos
create policy "Acceso total a insumos" on public.insumos for all using (true) with check (true);

-- Pedidos
create policy "Acceso total a pedidos" on public.pedidos for all using (true) with check (true);
create policy "Acceso total a detalle_pedidos" on public.detalle_pedidos for all using (true) with check (true);

-- Movimientos
create policy "Acceso total a movimientos" on public.movimientos for all using (true) with check (true);

-- Profiles (Stricter RBAC logic)
create policy "Users can read own profile" on public.profiles for select using ( auth.uid() = id or is_admin() );
create policy "Users can modify their own profile" on public.profiles for update using ( auth.uid() = id );

-- Storage Policies
create policy "Acceso público a productos" on storage.objects for select using ( bucket_id = 'productos' );
create policy "Subida pública a productos" on storage.objects for insert with check ( bucket_id = 'productos' );
create policy "Modificación pública a productos" on storage.objects for update using ( bucket_id = 'productos' );
create policy "Eliminación pública a productos" on storage.objects for delete using ( bucket_id = 'productos' );

create policy "Acceso público a clientes" on storage.objects for select using ( bucket_id = 'clientes' );
create policy "Subida pública a clientes" on storage.objects for insert with check ( bucket_id = 'clientes' );
create policy "Modificación pública a clientes" on storage.objects for update using ( bucket_id = 'clientes' );
create policy "Eliminación pública a clientes" on storage.objects for delete using ( bucket_id = 'clientes' );

-- 7. DEFAULT DATA
insert into public.configuracion (id, nombre_negocio)
values (1, 'Autolavado Gochi')
on conflict (id) do nothing;
